name: WinterCraft
main:  net.mcwintercraft.wintercraft.WinterCraft
version: 0.0.1
authors: [Markersx, Pentahexide]
load: STARTUP
depend: [ProtocolLib, Votifier]
commands:
   color:
      description: Opens ChatColor options.
      usage: /<command> <option> type /<command> help for a list of options.
      aliases: [chatcolor, chatcolors, c]
      permission: wintercraft.chatcolor
      permission-message: You don't have <permission>
   test:
      description: Test command to do what ever.
      usage: /<command>
      permission: wintercraft.test
      permission-message: You are not a scientits!
   vote:
      description: Vote links.
      usage: /vote
      permission: wintercraft.vote
      permission-message: Please report this to an admin thx <3
   website:
      description: Displays website link.
      usage: /website
      permission: wintercraft.website
      permission-message: Please report this to an admin thx <3
   rank:
      description: Displays all ranks.
      usage: /rank
      aliases: [ranks]
      permission: wintercraft.ranks
      permission-message: Please report this to an admin thx <3
   srfw:
      description: shoot random firework.
      usage: /<command> <player> <amount> <radius>
      permission: wintercraft.srfw
      permission-message: Pew Pew
   sound:
      description: Sound options
      usage: /<command>
      permission: wintercraft.chatsound
      permission-message: Please report this to an admin thx <3
   sl:
      description: Toggles spectator location reversion.
      usage: /<command>
      permission: sl.use
      permission-message: You're not allowed to do that.
   fakeop:
      description: Fake op players.
      usage: /<command> <player> or /<command> *
      permission: wintercraft.fakeop
      permission-message: Opped
   fakedeop:
      description: Fake deop players.
      usage: /<command> <player> or /<command> *
      permission: wintercraft.fakedeop
      permission-message: De-opped
   freeze:
      description: Freeze players.
      usage: /<command> <player>
      permission: wintercraft.freeze
      permission-message: You have been frozen
   marry:
      description: Marry anothe player.
      usage: /<command> <name>
      permission: wintercraft.marry
      permission-message: You don't have permission to marry this player
   playtime:
      description: Displays player time statistics
      usage: /<command> <player>
      permission: wintercraft.playtime
      permission-message: Please report this to an admin thx <3
   endercrate:
      description: EnderCrate stuff.
      usage: /<command> <create|key> <amount>
      permission: wintercraft.endercrate
      permission-message:
   enchants:
      description: Displays info about all enchantments.
      usage: /<command>
      permission: wintercraft.enchants
      permission-message: Please report this to an admin thx <3
   setwarp:
      description: Creates a new warp.
      usage: /<command> <warp>
      aliases: [createwarp,ecreatewarp,esetwarp]