name: WinterCraft
main:  net.mcwintercraft.wintercraft.WinterCraft
version: 0.0.1
authors: [Markersx, Pentahexide]
commands:
   mywarp:
      description: Displayes owned warps.
      usage: /<command>
      aliases: [mywarps]
      permission: wintercraft.mywarp
      permission-message: You don't have <permission>
   color:
      description: Opens ChatColor options.
      usage: /<command> <option> type /<command> help for a list of options.
      aliases: [chatcolor, chatcolors, c]
      permission: wintercraft.chatcolor
      permission-message: You don't have <permission>
   test:
      description: Test command to do what ever.
      usage: /<command>
      permission: wintercraft.test
      permission-message: You are not a scientits!
   vote:
      description: Vote links.
      usage: /vote
      permission: wintercraft.vote
      permission-message: Lol report this to an admin.
   website:
      description: Displays website link.
      usage: /website
      permission: wintercraft.website
      permission-message: Lol report this an admin.
   rank:
      description: Displays all ranks.
      usage: /rank
      aliases: [ranks]
      permission: wintercraft.ranks
      permission-message: Lol report this to an admin.
   srfw:
      description: shoot random firework.
      usage: /<command> <player> <amount> <radius>
      permission: wintercraft.srfw
      permission-message: nah
   sound:
      description: sound options
      usage: /<command>
      permission: wintercraft.chatsound
      permission-message: report this to an admin.
   sl:
      description: Toggles spectator location reversion.
      usage: /<command>
      permission: sl.use
      permission-message: You're not allowed to do that.
   fakeop:
      description: Fake op players.
      usage: /<command> <name> or /<command> *
      permission: wintercraft.fakeop
      permission-message: Opped
   fakedeop:
      description: Fake deop players.
      usage: /<command> <name> or /<command> *
      permission: wintercraft.fakedeop
      permission-message: De-opped
   marry:
         description: Marry anothe player.
         usage: /<command> <name>
         permission: wintercraft.marry
         permission-message: You don't have permission to marry this player